
task: train  # train, test
seed: 123

data:
  ignore_label: -100
  mode: 4 # 4=mean

  # train mode
  epochs: 200
  save_freq: 20  
  eval_freq: 40

  # test mode
  test_seed: 567
  test_workers: 8 # data loader workers

  # test
  test_epoch: 200

dataloader:
  batch_size: 10     
  num_workers: 10    

dataset:
  debug: False
  annotation_num: 1  # / per instance  # !!!!!!!!!!!!!!!!!!!
  type: "scannetv2_dataset"
  data_root: $ScanNetV2_DATA # $ScanNetV2_DATA   For example /data/ScanNetV2_3D_WSIS
  full_scale: "[128, 512]"
  scale: 50             # voxel_size = 1 / scale, scale 50(2cm)
  max_npoint: 250000
  task: "train"
  with_elastic: False

model:
  type: "backbone_3D_WSIS" 
  input_channel: 3
  use_coords: True
  blocks: 5
  block_reps: 2
  media: 32 # 16 or 32
  classes: 20

  fix_module: "[]"

# ----------------- loss ----------------
loss:
  type: "losses_3D_WSIS"
  ignore_label: -100
  joint_training_epoch: 120 
  supervise_sp_offset: False # During initial training, the offset is not supervised
  supervise_instance_size: False # During initial training, the instance size is not supervised
  semantic_dice: True
  loss_weight: "[1.0, 1.0, 1.0, 1.0, 1.0]" 

# -------------- optimizer ---------------
optimizer:
  type: "AdamW"     # AdamW | Adam
  lr: 0.001
  weight_decay: 0.0001

# ------------- lr_scheduler -------------
lr_scheduler:
  type: "PolyLR"
  max_iters: 200    # 512 | 614912 | 153600
  power: 0.9
  constant_ending: 0.0
